### ISSUE TITLE
Incomplete Gibbs Sampler Implementation

### ISSUE THREAD

**Issue by whatupbiatch** [arnim/HDP#3]
Hi,
I have read the code. The original paper build a gibbs chain for two level HDP with two sampling stage, sampling k and sampling t. whereas in this implementation only t variables are sampled and sampling table-topic assignment subroutine is called only when new tables are created. The original paper sampled all  table-topic assignment during every gibbs swap.
I'm confused. Is this an implementation bug or it is just another algorithm (maybe simplified) ?

**Comment by ziqilau** [comment]
I think you are right. The implementation of the optimization process is incomplete.

**Comment by arnim** [comment]
Indeed k_jt is only sampled if a new table is created.
The question is if the sampler still converges to the true posterior.
I'm hesitant to state so without seeing or giving any proof (maybe you are willing to look closer into it). However, it would require only little effort to call this step for already existing tables as well.
I could imagine that mixing improves - feel free to send me pull requests.

An other question is if you are interested for theoretical reasons (then this might be an interesting issue) or if you are in search for fast posterior inference (for possible large document collections) for the HDP. In the later case you might look at the more recent:

Online Variational Inference for the Hierarchical Dirichlet Process
http://www.cs.cmu.edu/~chongw/papers/WangPaisleyBlei2011.pdf

Truncation-free Stochastic Variational Inference for Bayesian Nonparametric Models
http://books.nips.cc/papers/files/nips25/NIPS2012_0208.pdf

Truly Nonparametric Online Variational Inference for Hierarchical Dirichlet Processes
http://cs.brown.edu/~sudderth/papers/nips12hdpOnline.pdf

**Comment by whatupbiatch** [comment]
thank you.
I'm currently looking for a fast posterior estimation algorithm for multilevel HDP( more than two level), Is there any applicable recent techniques faster than the original MCMC? The orginal MCMC could be easily adapted to multi level cases.

**Comment by arnim** [comment]
@whatupbiatch maybe its best you ask at
https://lists.cs.princeton.edu/mailman/listinfo/topic-models

While I'm (out of the box) not aware of any work that applies the Stochastic Variational paradigm to multilevel HDP it should be doable and maybe even interesting ;)
